### ISSUE TITLE
Fatal error while login in or register

### ISSUE THREAD

**Issue by delicacystudios** [shafygunawan/florafavs#1]
Website is absolutely as on GitHub, so I have no idea what is going on there.

`Fatal error: Uncaught Exception: could not find driver in /home/container/data/customer.php:53 Stack trace: #0 /home/container/libs/validation.php(126): get_customers() #1 /home/container/register.php(28): validate_email_customer(Array, Array, 'email') #2 {main} thrown in /home/container/data/customer.php on line 53`

**Comment by shafygunawan** [comment]
Hai @delicacystudios,

This error typically indicates that the PDO driver for the database you're trying to connect to is not installed or enabled in your PHP configuration.

Here are some steps you can take to troubleshoot this issue:

1. Check PHP Extensions: Ensure that the PDO extension and the specific PDO driver for your database (like pdo_mysql for MySQL) are installed and enabled. You can verify this by creating a simple PHP script with phpinfo(); and checking the output for the PDO section.
2. Update PHP Configuration: If the driver is not listed, you may need to enable it in your php.ini file. Look for lines like ;extension=pdo_mysql and remove the semicolon at the beginning.
3. Environment Setup: If you are using a containerized environment, ensure that the necessary extensions are included in your Dockerfile or container setup.
4. Server Status: Double-check that the database server is running and accessible from your application.
